# Generated by Django 2.1.7 on 2024-09-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_featued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featued',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
